services:
  dependencies:
    build: 
      context: .
      dockerfile: dependencies.Dockerfile
    image: dependencies
  webserver:
    build: src/webserver/
    image: webserver
    ports:
      - "${SALT_WEB_PORT}:443"
    environment:
      - SALT_WEB_PORT=443
  api:
    build: src/api/
    image: api
    ports:
      - "${SALT_API_PORT}:443"
    environment:
      - SALT_API_PORT=443
      - SALT_AUTH_PORT=${SALT_AUTH_PORT}
      - SALT_AUTH_ADDR=auth
      - SALT_USERS_PORT=${SALT_USERS_PORT}
      - SALT_USERS_ADDR=users
      - SALT_EMAIL_PORT=${SALT_EMAIL_PORT}
      - SALT_EMAIL_ADDR=email
      - SALT_WEB_PORT=${SALT_WEB_PORT}
  authdb:
    image: postgres
      #volumes:
      #- ./data/authdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=saltauthdb
      - POSTGRES_USER=saltauth
      - POSTGRES_PASSWORD=saltauth
    ports:
      - "9090:9090"
    command: -p 9090
  auth:
    build: src/auth/
    image: auth
    ports:
      - "${SALT_AUTH_PORT}:${SALT_AUTH_PORT}"
    environment:
      - SALT_AUTH_PORT=${SALT_AUTH_PORT}
      - SALT_USERS_PORT=${SALT_USERS_PORT}
      - SALT_USERS_ADDR=users
      - AUTHDB_HOST=authdb
      - AUTHDB_PORT=9090
  usersdb:
    image: postgres
    environment:
      - POSTGRES_DB=saltusersdb
      - POSTGRES_USER=saltusers
      - POSTGRES_PASSWORD=saltusers
    ports:
      - "9091:9091"
    command: -p 9091
  users:
    build: src/users
    image: users
    ports:
      - "${SALT_USERS_PORT}:${SALT_USERS_PORT}"
    environment:
      - SALT_USERS_PORT=${SALT_USERS_PORT}
      - SALT_AUTH_PORT=${SALT_AUTH_PORT}
      - SALT_AUTH_ADDR=auth
      - SALT_EMAIL_PORT=${SALT_EMAIL_PORT}
      - SALT_EMAIL_ADDR=email
      - USERSDB_HOST=usersdb
      - USERSDB_PORT=9091
  emaildb:
    image: postgres
    environment:
      - POSTGRES_DB=saltemaildb
      - POSTGRES_USER=saltemail
      - POSTGRES_PASSWORD=saltemail
    ports:
      - "9092:9092"
    command: -p 9092
  email:
    build: src/email
    image: email
    ports:
      - "${SALT_EMAIL_PORT}:${SALT_EMAIL_PORT}"
    environment:
      - SALT_EMAIL_PORT=${SALT_EMAIL_PORT}
      - SALT_USERS_PORT=${SALT_USERS_PORT}
      - SALT_USERS_ADDR=users
      - EMAILDB_HOST=emaildb
      - EMAILDB_PORT=9092


