name: Docker compose
on: [push]

jobs:
  build:
    environment: buildenv
    runs-on: ubuntu-latest
    env:
      SALT_WEB_PORT: 8080
      SALT_API_PORT: 8081
      SALT_AUTH_PORT: 8082
      SALT_USERS_PORT: 8083
      SALT_EMAIL_PORT: 8084
      SALT_CONTENT_PORT: 8085
      RECAPTCHA_SITE_KEY: ${{secrets.RECAPTCHA_SITE_KEY}}
      RECAPTCHA_PROJECT: projects/saltgram
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      REF_SECRET_KEY: ${{secrets.REF_SECRET_KEY}}
      TOKEN_TIMEOUT_MINUTES: 1
      TIME_LAYOUT: 2006-01-02 15:04:05 -0700 MST
      GOOGLE_APPLICATION_CREDENTIALS: $HOME/secrets/saltgram-c0751de619fa.json
      SALT_GDRIVE_CREDS: $HOME/secrets/saltgram-service-key.json
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/checkout@v2
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt.sh
        env:
          SECRETS_PASSPHRASE: ${{secrets.SECRETS_PASSPHRASE}}
      - name: View port usage
        run: sudo lsof -i -P -n | grep LISTEN

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
